### ISSUE TITLE
Pixel car racer in app purchased not working

### ISSUE THREAD

**Issue by Arrrrrrrrrrrrrriiiiii** [Flixbox/lp-compat#100]
I have used both the proxy server and reassembly dex but the shop just says that there is no Internet connection and does not let me buy anything

**Comment by Flixbox** [comment]
This repo is for maintaining the compatibility list. Please refer to [this post](https://www.reddit.com/r/luckypatcher/comments/xan461/website_discord_compatibility_list_wiki_all_other/) for some troubleshooting. There's a Discord as well.

**Comment by 2chiefk** [comment]
I'm sorry this guy's not apparently very reliable he wants somebody that can get you the Lucky Patcher that's reliable just ask
