### ISSUE TITLE
found a new issue

### ISSUE THREAD

**Issue by Ginger334** [Flixbox/lp-compat#76]
so for some reason when I was search for Cat Game - The Cats Collector!  instead of Cat Game - The Cats Collector! I got two same games that I already added 

![image](https://github.com/Flixbox/lp-compat/assets/139046418/93670bd9-4974-4a75-8078-f51717bf6d5a)

**Comment by Flixbox** [comment]
I think you can just hit the refresh button to make this go away 🤔
